spring:
  profiles:
    active: dev
  application:
    name: timelog
  datasource:
    username: user
    password: secret2
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 5000
  jpa:
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
server:
  servlet:
    context-path: /api/v1
